log:
  level: info

upstreams:
  - tag: AliDNS
    type: quic
    address: 223.5.5.5

  - tag: Google
    type: tls
    address: 8.8.8.8
    #socks5:
    #  address: 127.0.0.1:1080

#  - tag: Google-UDP
#    type: udp
#    address: 8.8.8.8
#
#  - tag: Google-TCP
#    type: tcp
#    address: 8.8.8.8
#
#  - tag: Google-DoH
#    type: https
#    address: 8.8.8.8
#    # use-http3: true # Use HTTP/3
#
#  - tag: AdGuard-DoQ
#    type: quic
#    address: 94.140.14.14:784
#    servername: dns.adguard-dns.com # TLS SNI


plugin-matchers:
  - tag: geosite
    type: sing-geosite # https://github.com/SagerNet/sing-geosite
    args:
      path: /path/to/geosite.db
      code: cn

workflows:
  - tag: default
    rules:
      - match-and:
          - plugin: # Use Plugin Matcher
              tag: geosite # Plugin Matcher Tag
              args: cn # SingGeoSite: Match code `cn`
        exec: # Run Executors if match successfully
          - upstream: AliDNS # Send Request to upstream `AliDNS`
        else-exec:
          - upstream: Google # Send Request to upstream `Google`

listeners:
  - tag: TCP
    type: tcp
    listen: :53 # Listen [::]:53
    workflow: default # Workflow Tag

  - tag: UDP
    type: udp
    listen: :53 # Listen [::]:53
    workflow: default # Workflow Tag

#  - tag: TLS
#    type: tls
#    listen: :853
#    server-cert-file: /path/to/cert.pem
#    server-key-file: /path/to/key.pem
#
#  - tag: HTTPS
#    type: https
#    listen: :443
#    server-cert-file: /path/to/cert.pem
#    server-key-file: /path/to/key.pem
#
#  - tag: QUIC
#    type: quic
#    listen: :853
#    enable-0rtt: true # 0RTT Support (QUIC)
#    server-cert-file: /path/to/cert.pem
#    server-key-file: /path/to/key.pem

